# Build arguments
ARG IMAGE=webdevops/php-nginx-dev:alpine-php7
ARG APP_PATH=.
FROM ${IMAGE}

# TimeZone
RUN apk add --no-cache tzdata
RUN cp /usr/share/zoneinfo/Europe/Rome /etc/localtime
RUN apk del tzdata

# Add Memcached
RUN apk add --no-cache --upgrade php7-memcached

# Add prestissimo
RUN composer global require "hirak/prestissimo"